### ISSUE TITLE
Usar IRulesBuilder para permitir aplicar a regra independente da ordem

### ISSUE THREAD

**Issue by augustocb23** [FernandoDona/documento-br#1]
A implementação atual de `FluentValidationExtensions` usa `IRuleBuilderInitial`, que só está disponível ao declarar a regra (método `RuleFor(...)`). Se a implementação utilizar `IRuleBuilder` ficará mais flexível, permitindo que a extensão também seja usada após outras validações, como `NotNull()` e `NotEmpty()`

**Comment by FernandoDona** [comment]
Subi a alteração sugerida hoje
